### PR TITLE
Replace sys.exit(1) to exception chaining for ability catch and recovery

### PR DESCRIPTION
**Pull request by mrkeuz**

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
close #20

**Review by AtsushiSakai — APPROVED** [review]
LGTM. Thank you for great improvement!!

**Comment by AtsushiSakai** [comment]
Do you need a new release for PyPi?

**Comment by mrkeuz** [comment]
As it is convenient for you. It's not very urgent for me.

**Pull request merged**
