### PR TITLE
implemented API to get Sensor Packets

### LINKED ISSUE #10: Implement API to get Sensor Packets

### PR DESCRIPTION
**Pull request by rforro**
Implementation of the API to get sensor value. I've done only the basics structure plus sensors which I need. Feel free to extend it.

This closes #10

### CODE REVIEW

**Review by AtsushiSakai — COMMENTED** [review]
Thank you so much for great PR!!. Is it possible to add manual in README.md? If it is difficult, I can do that.

**Comment by rforro** [comment]
I've updated the `README.md`, but not documentation. Should I update it as well?

Second question: How would you document which sensors can be requested? Basically content of following table:
```
SENSOR = {
        # "Name", (Packet ID, Data Bytes, signed)
        "Charging State": (21, 1, False),
        "Voltage": (22, 2, False),
        "Current": (23, 2, True),
        "Temperature": (24, 1, True),
        "Battery Charge": (25, 2, False),
        "Battery Capacity": (26, 2, False),
        "OI Mode": (35, 1, False)
    }
```

**Comment by AtsushiSakai** [comment]
> but not documentation. Should I update it as well?

Thank you. Yes. If you can, please do it.

>  How would you document which sensors can be requested? 

I think already `start_data_stream` doc-string explains it. Do you think it is not enough?

**Comment by rforro** [comment]
Docs is updated as well. You are right its enough to list all sensors inside the `data_stream_start` method.

**Review by AtsushiSakai — APPROVED** [review]
LGTM. Thank you for great PR!!. I will release a new version soon.

**Pull request merged**
